# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{mattscilipoti-model_steps}
  s.version = "0.3.7"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Matt Scilipoti", "Chris Cahoon"]
  s.date = %q{2010-12-15}
  s.description = %q{Step Definitions for cucumber which support ActiveRecord Models}
  s.email = %q{matt@scilipoti.name}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "Gemfile",
     "Gemfile.lock",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "examples/example_helper.rb",
     "examples/mattscilipoti-model_steps_example.rb",
     "features/mattscilipoti-model_steps.feature",
     "features/step_definitions/mattscilipoti-model_steps_steps.rb",
     "features/support/env.rb",
     "lib/mattscilipoti-model_steps.rb",
     "lib/model_steps/step_definitions.rb",
     "mattscilipoti-model_steps-0.3.4.gem",
     "mattscilipoti-model_steps.gemspec",
     "test/test_step_definition.rb"
  ]
  s.homepage = %q{http://github.com/mattscilipoti/mattscilipoti-model_steps}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Model Steps for cucumber}
  s.test_files = [
    "test/test_step_definition.rb",
     "examples/example_helper.rb",
     "examples/mattscilipoti-model_steps_example.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>, [">= 2.1.0"])
      s.add_runtime_dependency(%q<aaronh-chronic>, ["~> 0.3.9"])
      s.add_runtime_dependency(%q<cucumber>, ["~> 0.9.4"])
      s.add_runtime_dependency(%q<friendly_id>, ["~> 3.0"])
      s.add_runtime_dependency(%q<i18n>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<minitest>, ["~> 2.0"])
      s.add_development_dependency(%q<timecop>, ["~> 0.3"])
    else
      s.add_dependency(%q<activesupport>, [">= 2.1.0"])
      s.add_dependency(%q<aaronh-chronic>, ["~> 0.3.9"])
      s.add_dependency(%q<cucumber>, ["~> 0.9.4"])
      s.add_dependency(%q<friendly_id>, ["~> 3.0"])
      s.add_dependency(%q<i18n>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<minitest>, ["~> 2.0"])
      s.add_dependency(%q<timecop>, ["~> 0.3"])
    end
  else
    s.add_dependency(%q<activesupport>, [">= 2.1.0"])
    s.add_dependency(%q<aaronh-chronic>, ["~> 0.3.9"])
    s.add_dependency(%q<cucumber>, ["~> 0.9.4"])
    s.add_dependency(%q<friendly_id>, ["~> 3.0"])
    s.add_dependency(%q<i18n>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<minitest>, ["~> 2.0"])
    s.add_dependency(%q<timecop>, ["~> 0.3"])
  end
end

